import rclpy

from terasim_cosim.constants import *
from terasim_cosim.redis_msgs import SUMOSignalDict
from terasim_cosim.redis_client_wrapper import create_redis_client

from rclpy.node import Node
from autoware_perception_msgs.msg import (
    TrafficSignal,
    TrafficSignalArray,
    TrafficSignalElement,
)

# SUMO TLS ID -> Lanelet2 regulatory element ID mapping
# Generated by matching SUMO junction positions to lanelet2 traffic light
# regulatory elements in the AA_Fixed_V6 map.
SUMO_TO_LANELET2_TLS = {
    "29311341": 735994,
    "62477148": 737664,
    "62484827": 735932,
    "62486064": 736814,
    "62486066": 736058,
    "62487316": 736158,
    "62488532": 736672,
    "62490467": 736766,
    "62490469": 735946,
    "62492569": 736020,
    "62493963": 736562,
    "62495459": 736488,
    "62497103": 736324,
    "62498701": 737636,
    "62500567": 736012,
    "62500958": 736516,
    "62501598": 736712,
    "62502883": 736222,
    "62505160": 736578,
    "62506219": 736918,
    "62509629": 736436,
    "62510979": 736930,
    "62514285": 736268,
    "62514387": 736896,
    "62517097": 736352,
    "62523458": 736124,
    "62527454": 736838,
    "62527484": 737650,
    "62530034": 736608,
    "62532012": 736680,
    "62544183": 735968,
    "62547338": 736036,
    "62547347": 736282,
    "62550570": 737670,
    "62550575": 736080,
    "62563350": 736454,
    "62565682": 736730,
    "62573187": 736696,
    "62593488": 736548,
    "62596442": 736252,
    "62601733": 736782,
    "62609566": 736196,
    "62609606": 736098,
    "62615397": 736468,
    "62616829": 736862,
    "62618800": 736744,
    "767530322": 736178,
    "cluster_62477163_62500824": 736400,
}


class AutowareTLSPlugin(Node):
    def __init__(self):
        super().__init__("autoware_tls_plugin")

        # Publisher for TrafficSignalArray
        self.pub_signal_array = self.create_publisher(
            TrafficSignalArray,
            "/perception/traffic_light_recognition/traffic_signals",
            10,
        )

        # Timer setup
        timer_period = 0.05
        self.timer = self.create_timer(timer_period, self.on_timer)

        self.on_start()

        self.get_logger().info(
            f"Starting autoware traffic light interface with redis... "
            f"({len(SUMO_TO_LANELET2_TLS)} TLS mappings)"
        )

    def on_start(self):
        key_value_config = {TLS_INFO: SUMOSignalDict}
        self.redis_client = create_redis_client(key_value_config=key_value_config)

    def on_timer(self):
        try:
            tls_info = self.redis_client.get(TLS_INFO)
        except Exception:
            return

        if tls_info:
            data = tls_info.data
            signals = self.get_signal_info(data)

            traffic_signal_array = TrafficSignalArray()
            traffic_signal_array.stamp = self.get_clock().now().to_msg()
            traffic_signal_array.signals = signals

            self.pub_signal_array.publish(traffic_signal_array)

    def get_signal_info(self, traffic_signals_tls_info):
        signals = []

        for sumo_tls_id, info in traffic_signals_tls_info.items():
            lanelet2_id = SUMO_TO_LANELET2_TLS.get(sumo_tls_id)
            if lanelet2_id is None:
                continue  # No mapping for this TLS

            # Get the dominant state for this TLS
            # SUMO state string has one char per signal link (e.g. "rrGGgrrrGGg")
            # We use the first non-red state to determine the overall color
            state = info.tls
            if not state:
                continue

            # Determine overall color: if any green → green, elif any yellow → yellow, else red
            if "G" in state or "g" in state:
                color = TrafficSignalElement.GREEN
            elif "y" in state or "Y" in state:
                color = TrafficSignalElement.AMBER
            else:
                color = TrafficSignalElement.RED

            traffic_signal_element = TrafficSignalElement()
            traffic_signal_element.shape = TrafficSignalElement.CIRCLE
            traffic_signal_element.status = TrafficSignalElement.SOLID_ON
            traffic_signal_element.confidence = 1.0
            traffic_signal_element.color = color

            traffic_signal = TrafficSignal()
            traffic_signal.traffic_signal_id = lanelet2_id
            traffic_signal.elements = [traffic_signal_element]
            signals.append(traffic_signal)

        return signals


def main(args=None):
    rclpy.init(args=args)
    autoware_tls_plugin = AutowareTLSPlugin()
    rclpy.spin(autoware_tls_plugin)
    autoware_tls_plugin.destroy_node()
    rclpy.shutdown()


if __name__ == "__main__":
    main()
