"""
Autoware Traffic Light Plugin (HTTP)

Syncs traffic light states from TeraSim (HTTP API) to Autoware.

Map: Ann Arbor NCRC area
- 44 SUMO TLS mapped to Autoware regulatory elements
- Regulatory elements: 674183-675445
- Generated by geographic + direction matching between SUMO lane endpoints
  and lanelet2 stop line positions (20m distance, 0.7 cosine similarity)
"""

import requests
import rclpy
from rclpy.node import Node
from std_msgs.msg import Float64
from builtin_interfaces.msg import Time as TimeMsg
from autoware_perception_msgs.msg import (
    TrafficSignal,
    TrafficSignalArray,
    TrafficSignalElement,
)


# Ann Arbor NCRC area (AA_Fixed_V12 - complete route coverage)
# Each reg_elem maps to all SUMO links from its approach edge.
# Aggregation: least-restrictive (GREEN > AMBER > RED).
SUMO_TO_AUTOWARE_TLS_MAPPING = {
    '29311341': [(775195, 0), (775197, 0), (775196, 1), (774970, 5), (774971, 6)],
    '62477148': [(775193, 0), (775164, 3), (775164, 4), (775165, 4), (775163, 5), (774706, 6), (774707, 8)],
    '62486064': [(774772, 0), (774772, 1), (774773, 1), (775135, 5), (774769, 9), (774768, 9), (775183, 13)],
    '62486066': [(774760, 1), (775182, 5), (774762, 9), (775160, 13)],
    '62487316': [(774467, 1), (774466, 2), (774959, 4), (774958, 5), (775005, 8)],
    '62490467': [(774746, 0), (774746, 1), (774747, 1), (774745, 2), (774746, 3), (775049, 6), (774749, 9), (774750, 9), (774748, 10), (774751, 11), (774567, 14)],
    '62490469': [(775096, 1), (774568, 5), (774363, 9), (775015, 13)],
    '62492569': [(774445, 1)],
    '62493581': [(774909, 1), (774910, 3), (774609, 5), (774608, 6), (774928, 7), (775017, 10), (774606, 13), (774604, 14), (774605, 14), (774603, 15), (774606, 16)],
    '62494762': [(774358, 0), (774358, 1), (775295, 0), (774357, 3), (774580, 4), (774412, 5), (774413, 5), (774581, 5)],
    '62500567': [(774664, 0), (774664, 1), (774665, 1), (774663, 2), (774669, 3), (774670, 4), (774668, 5), (774642, 6), (774643, 8)],
    '62500641': [(774654, 0), (774653, 1), (774862, 4), (774861, 5), (774857, 6), (774858, 8)],
    '62500943': [(774850, 0), (774849, 2), (775188, 5), (775188, 6), (775189, 7), (774597, 8), (774595, 9), (774596, 11)],
    '62500958': [(775120, 0), (775119, 1), (774852, 5), (774851, 6), (775191, 8), (775192, 9), (775190, 10)],
    '62501419': [(774771, 0), (774771, 1), (774770, 2), (774364, 5), (774365, 7), (774765, 9), (774766, 11), (774767, 11), (775036, 13)],
    '62501571': [(774573, 0), (774573, 1), (774573, 2), (774574, 1), (774575, 1), (774783, 10), (774784, 10), (774491, 11), (774782, 11), (774781, 12)],
    '62501598': [(774685, 0), (774685, 1), (774686, 0), (775037, 3), (775038, 6), (774474, 8), (774475, 8), (774723, 8), (774722, 9), (774724, 9)],
    '62506219': [(774614, 0), (774615, 0), (774613, 1), (774893, 3), (774894, 4), (774408, 5), (774408, 6), (774409, 6), (774847, 6), (774848, 6), (774846, 7), (774881, 7)],
    '62514378': [(774638, 0), (774638, 1), (774639, 1), (774637, 2), (774638, 3), (774638, 4), (774733, 6), (774755, 10), (774756, 13), (774757, 13), (774510, 15)],
    '62517097': [(774433, 1), (774434, 1), (774432, 2), (774908, 6), (774907, 7), (774934, 9), (774934, 10), (774935, 11), (774938, 12), (774934, 13), (774904, 15), (774905, 17)],
    '62527484': [(774758, 0), (774758, 1), (774759, 1), (775093, 1), (775094, 1), (775090, 2), (775091, 2), (775092, 2), (775078, 4), (775077, 5), (775141, 7), (775056, 10), (775055, 11), (775054, 12)],
    '62527486': [(774740, 1), (775053, 5), (775052, 6), (774761, 10), (774780, 14), (774778, 15), (774779, 17)],
    '62532012': [(775167, 0), (775167, 1), (774705, 2), (774709, 2), (774710, 2), (775166, 2), (774679, 3), (774680, 3), (774678, 4), (775061, 7), (775062, 9)],
    '62537809': [(774565, 1), (774564, 3), (774720, 5), (774720, 6), (774719, 7), (774720, 8), (774550, 10), (774549, 11), (774744, 12), (774355, 14)],
    '62537929': [(774864, 1), (774865, 1), (774830, 2), (774977, 6), (774978, 9), (774976, 10), (774527, 12), (774527, 13), (774527, 14), (774819, 14), (774526, 15), (774818, 15), (774523, 16), (774525, 16), (774528, 16), (774817, 16), (774826, 20), (775152, 20), (775153, 20), (775151, 21), (774825, 23)],
    '62542022': [(775158, 1), (775098, 10), (775076, 14), (775075, 15)],
    '62543483': [(774896, 0), (774895, 1), (774898, 5), (774897, 7), (774411, 10), (774410, 11)],
    '62550570': [(774619, 0), (774619, 1), (774620, 1), (774618, 3), (775243, 3), (775243, 4), (775149, 5), (775150, 5), (775148, 6), (775147, 7), (774378, 11), (774376, 12), (774377, 14), (774823, 16), (774824, 16), (774822, 17)],
    '62551656': [(774646, 1), (774645, 2), (774531, 4), (774529, 8)],
    '62554263': [(774660, 1), (775099, 5), (775184, 9), (774473, 13)],
    '62559632': [(775097, 1), (774438, 5), (774440, 9), (775127, 13)],
    '62559635': [(774439, 1), (774497, 5), (774361, 9)],
    '62563769': [(775140, 0), (775140, 1), (775140, 2), (775140, 3), (775128, 5), (774640, 9), (774641, 11), (775100, 13)],
    '62565682': [(774919, 0), (774920, 0), (774918, 1), (774917, 2), (774943, 6), (774944, 6), (774942, 7), (774926, 11), (774927, 11), (774925, 12), (774924, 13), (774986, 15), (774986, 16), (774987, 16), (774940, 17), (775292, 18), (774985, 19), (775292, 19)],
    '62578784': [(774560, 0), (774559, 1), (774560, 2), (774560, 3), (774584, 4), (774465, 8), (774464, 9)],
    '62601699': [(774373, 0), (774372, 5), (775241, 8), (775241, 9), (775241, 10), (775241, 11)],
    '62601733': [(774841, 1), (774842, 1), (774884, 2), (774890, 6), (774891, 8), (774876, 9), (774876, 10), (774877, 10), (774875, 11), (774887, 15), (774886, 16)],
    '62609606': [(774385, 1), (774883, 5), (774882, 6), (774388, 9), (774829, 12), (774829, 13), (774828, 14), (774829, 15)],
    '665630433': [(774414, 1), (774566, 5), (774741, 9), (774569, 13)],
    '767530322': [(774687, 1), (774683, 4), (774683, 5), (774682, 6), (774484, 10), (774485, 10), (774478, 14), (774477, 15), (774476, 15)],
    'GS_11332562158': [(774375, 0), (774375, 1), (774374, 2), (774375, 3), (774375, 4), (775059, 6), (775060, 8), (774553, 10), (774554, 13), (775081, 15), (775080, 16)],
    'cluster4939301096_5007412744_5624574722': [(774547, 1), (774548, 2), (775123, 4), (774469, 7), (774468, 8), (775117, 11)],
    'cluster_62477163_62500824': [(774490, 1), (774488, 2), (774489, 3), (774587, 4), (774588, 4), (774586, 5), (774585, 6), (775242, 7), (774624, 9), (774625, 9), (774623, 10), (774404, 14), (774405, 14), (774406, 15), (774403, 16), (774407, 16)],
    'cluster_62484035_62484037': [(774482, 1), (774483, 3), (774508, 4), (774509, 4), (774507, 5), (774508, 6), (774506, 7), (774508, 8), (774992, 10), (774991, 12), (775105, 13), (775106, 13), (775104, 14), (775103, 15)],
    'cluster_62500913_62548685': [(774591, 1), (774592, 1), (774590, 2), (774522, 4), (774520, 5), (774521, 6), (774519, 7), (775083, 10), (775084, 10), (775082, 11), (774657, 15), (774658, 15), (774656, 16), (774655, 17)],
}


class AutowareTLSPlugin(Node):

    def __init__(self, **kwargs):
        super().__init__("autoware_tls_plugin", **kwargs)

        # Declare parameters
        self.declare_parameter("http_host", "localhost")
        self.declare_parameter("http_port", 8000)
        self.declare_parameter("simulation_id", "")

        self.http_host = self.get_parameter("http_host").value
        self.http_port = self.get_parameter("http_port").value
        self.simulation_id = self.get_parameter("simulation_id").value

        self.base_url = f"http://{self.http_host}:{self.http_port}"
        self.session = requests.Session()

        # Publisher
        self.pub_traffic_signals = self.create_publisher(
            TrafficSignalArray,
            "/perception/traffic_light_recognition/traffic_signals",
            10,
        )

        # Event-driven: subscribe to tick_complete instead of polling on timer
        self.sub_tick = self.create_subscription(
            Float64, '/terasim/tick_complete', self.on_tick, 10
        )

        # Re-publish cached signals periodically so Autoware never sees stale data
        self.republish_timer = self.create_timer(0.1, self.republish)
        self._last_msg = None

        # State cache
        self.last_state = None
        self._sim_time = 0.0

        self.get_logger().info(f"TLS plugin started: {self.base_url}, sim_id={self.simulation_id}")

    def _get_state(self):
        """Get simulation state from TeraSim HTTP API."""
        if not self.simulation_id:
            return None
        try:
            resp = self.session.get(
                f"{self.base_url}/simulation/{self.simulation_id}/state",
                timeout=0.5
            )
            self.last_state = resp.json()
            self._sim_time = self.last_state.get("simulation_time", 0.0)
            return self.last_state
        except:
            return self.last_state

    def on_tick(self, tick_msg):
        """Called once per SUMO step — publish traffic light states to Autoware."""
        self._sim_time = tick_msg.data

        state = self._get_state()
        if not state or "traffic_light_details" not in state:
            return

        signals = {}

        # Each reg_elem maps to exactly 1 SUMO link (straight-priority dedup).
        # No aggregation needed. Priority kept for safety if duplicates exist.
        COLOR_PRIORITY = {
            TrafficSignalElement.GREEN: 0,
            TrafficSignalElement.AMBER: 1,
            TrafficSignalElement.RED: 2,
        }
        color_map = {
            'r': TrafficSignalElement.RED,
            'y': TrafficSignalElement.AMBER,
            'g': TrafficSignalElement.RED,   # permissive green -> RED (only turn on protected)
            'G': TrafficSignalElement.GREEN,  # protected green -> GREEN
        }

        # Process each SUMO traffic light
        for tls_id, tls_info in state["traffic_light_details"].items():
            state_str = tls_info.get("tls", "") if isinstance(tls_info, dict) else tls_info

            # Map to Autoware regulatory elements
            # A reg_elem may have multiple link indices (e.g. shared between straight/turn).
            # Use LEAST RESTRICTIVE: if ANY link is GREEN, signal is GREEN.
            for reg_id, lane_idx in SUMO_TO_AUTOWARE_TLS_MAPPING.get(tls_id, []):
                light = state_str[lane_idx] if lane_idx < len(state_str) else 'r'
                color = color_map.get(light, TrafficSignalElement.RED)

                if reg_id in signals:
                    # Keep the least restrictive color (lowest priority = more permissive)
                    existing = signals[reg_id].elements[0].color
                    if COLOR_PRIORITY.get(color, 0) < COLOR_PRIORITY.get(existing, 0):
                        signals[reg_id].elements[0].color = color
                else:
                    elem = TrafficSignalElement()
                    elem.shape = TrafficSignalElement.CIRCLE
                    elem.status = TrafficSignalElement.SOLID_ON
                    elem.confidence = 1.0
                    elem.color = color

                    sig = TrafficSignal()
                    sig.traffic_signal_id = reg_id
                    sig.elements = [elem]
                    signals[reg_id] = sig

        # Use the node's clock (sim time if use_sim_time=true, wall clock otherwise)
        # This ensures the stamp always matches what Autoware expects
        msg = TrafficSignalArray()
        msg.stamp = self.get_clock().now().to_msg()
        msg.signals = list(signals.values())
        self.pub_traffic_signals.publish(msg)
        self._last_msg = msg  # cache for re-publish

    def republish(self):
        """Re-publish cached TLS signals with fresh timestamp to prevent staleness."""
        if self._last_msg is not None:
            self._last_msg.stamp = self.get_clock().now().to_msg()
            self.pub_traffic_signals.publish(self._last_msg)


def main(args=None):
    rclpy.init(args=args)
    node = AutowareTLSPlugin()
    rclpy.spin(node)
    node.destroy_node()
    rclpy.shutdown()


if __name__ == "__main__":
    main()
